baseUrl = 'https://blog.chikastory.com'
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
languageCode = 'zh-Hant'
theme = 'hugo-github-theme'
title = 'Chika story'
hasCJKLanguage = true
timeZone = 'Asia/Taipei'
