[profile]
author = 'Chika Chang'
githubUsername = 'chikastory'
status = ':anchor:'
statusMessage = 'hello, world'
description = 'Unity game developer of WooLFIDEA'
displayFollowers = true
organization = 'WooLFIDEA'
location = 'Taipei, Taiwan'
email = '13810485+chikastory@users.noreply.github.com'
displayEmail = false
url = 'blog.chikastory.com'
displayProBadge = true
createdDate = 2022-09-24T12:19:08Z

[[profile.badges]]
title = 'rss'
url = 'index.xml'
icon = "https://img.shields.io/badge/RSS-FFA500?style=for-the-badge&logo=rss&logoColor=white"
