name: Deploy pages

on:
    push:
        branches: ["main"]
    schedule:
        - cron:  '0 19 * * *'
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: latest
                  extended: true
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: true
                  fetch-depth: 0
            - name: Download public
              uses: actions/checkout@v3
              with:
                  repository: chikastory/chikastory.github.io
                  path: public
            - name: Build site
              run: hugo --minify --environment production
            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: site
                  path: public
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: site
            - name: Deploy
              id: deployment
              uses: peaceiris/actions-gh-pages@v3
              with:
                  deploy_key: ${{ secrets.PAGES_DEPLOY_KEY }}
                  external_repository: chikastory/chikastory.github.io
                  publish_branch: main
                  publish_dir: .
                  force_orphan: true
